/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_greenbamboo_prescholleducation_MediaFramework_GMediaFramework_GMediaFrameworkHolder */

#ifndef _Included_com_greenbamboo_prescholleducation_MediaFramework_GMediaFramework_GMediaFrameworkHolder
#define _Included_com_greenbamboo_prescholleducation_MediaFramework_GMediaFramework_GMediaFrameworkHolder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
